version: '3.3'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  prom_grafana_net:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    networks:
      - prom_grafana_net
    # volumes:
    #   - ./:/app 

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus 
      - prometheus_data:/prometheus 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090 
    networks:
      - prom_grafana_net
    links:
      - app:app.localhost
    restart: always

  grafana:
    image: grafana/grafana 
    user: '472'
    volumes: 
      - ./grafana_data:/var/lib/grafana_data
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/grafana.ini
    ports: 
      - 3000:3000
    networks: 
      - prom_grafana_net
    depends_on:
      - prometheus 
    restart: always



